### ISSUE TITLE
it doesn't work with anki - the newest version

### ISSUE THREAD

**Issue by peschiber** [HelenFoster/AnkiSpreadsheetImportPlus#7] opened 2022-01-08 07:31 UTC
starting anki I get the message that Anki doesn't work with Add-on AnkiSpreadsheetImportPlus.
**Even worth:
Having ignored that warning: now Anki doesn't start anymore.**
That's the reason, why I can't tell you the version of Anki, but it is the latest.

**Comment by peschiber** [comment] 2022-01-08 09:14
the error message is:
![Anki Errormessage for Excel addon](https://user-images.githubusercontent.com/97332023/148638795-65ea7817-69f2-443a-9fd2-d4ee8df678a1.png)

**Comment by CommanderPho** [comment] 2022-01-12 22:18
Seems to be a Duplicate of #6 (failing with the same Python error). In my instance, ignoring the message does not result in Anki failing to start even after quitting and re-opening several times, although the plugin still doesn't function.

**Comment by CommanderPho** [comment] 2022-01-13 00:25
I've implemented a fix in my pull request #8 
You may fetch this branch to try out the changes. I hope it helps.

**Comment by peschiber** [comment] 2022-01-13 00:58
Dear Helen,
thanks for your note.
I'll figure it out the next days.
I should stop spending so much time as beginner get familiar with Anki and translating that incredible deck "9000 sentences Spanish ...) from Spanish to German including audio-samples for Germans volunteer who come to Central America.

I'll give you a feed-back as soon as possible.
Nonetheless: thanks for the fantastic work you have done.

One Question:
as I've deleted your add-on, can you tell me the new code for your fixed add-on?

Peter El Salvador

**Comment by peschiber** [comment] 2022-01-13 01:07
Dear Helen,
since you seem to know a lot about programming when concerns Anki,
it would be very nice if you could have a look at my queries on the Anki forum.

As someone who is currently trying to figure out how Anki can support foreign language learning, I posted some questions. Till now, I'm not very familiar with Anki.
Therefore I am thrilled at how many nice people are trying to support me on the forum.

Unfortunately, however, I have not yet received an answer to a question that is important to me.
Keyword:  "Call up another map for additional information?".

Maybe you have a suggestion for a solution.
Thank you, Peter El Salvador

**Comment by CommanderPho** [comment] 2022-01-13 01:11
> Dear Helen, thanks for your note. I'll figure it out the next days. I should stop spending so much time as beginner get familiar with Anki and translating that incredible deck "9000 sentences Spanish ...) from Spanish to German including audio-samples for Germans volunteer who come to Central America.
> 
> I'll give you a feed-back as soon as possible. Nonetheless: thanks for the fantastic work you have done.
> 
> One Question: as I've deleted your add-on, can you tell me the new code for your fixed add-on?
> 
> Peter El Salvador

Hi Peter,

I'm actually not Helen (the original author of the plugin). My name is Pho Hale and I'm just another user who ran into the issue just like you. I changed the source code to fix it. Before the official add-on is updated on the Anki website, Helen will have to review and accept my proposed changes. In the meantime I can offer you a version you can download and install manually: 

[pho_hale_spreadsheet_import_plus.zip](https://github.com/HelenFoster/AnkiSpreadsheetImportPlus/files/7858990/pho_hale_spreadsheet_import_plus.zip)

Here is a Google Drive link to the same file:
https://drive.google.com/file/d/1xE54LC5X0JzxWckp-v8eq_hhOa4h5yF2/view?usp=sharing

Just click the "Install from a File..." button and select the .ankiaddon file (you must extract it from the .zip first if you use the non-Google Drive version).

**Comment by HelenFoster** [comment] 2022-01-19 18:42
Fixed! I don't really have any thoughts on the other thing.

**Closed as completed by HelenFoster** 2022-01-19 18:42 UTC
